// Etiquetas legibles para las columnas de EquipamientoModelo.
// Compartido entre la vista (EquipamientoView) y el form (FormularioEquipamiento)
// para que ambos muestren los mismos nombres lindos.

export const EQUIP_LABELS: Record<string, string> = {
  // --- Dimensiones y neumáticos ---
  Largo: "Largo (mm)",
  Ancho: "Ancho (mm)",
  Altura: "Altura (mm)",
  DistanciaEjes: "Distancia entre ejes (mm)",
  PesoOrdenMarcha: "Peso orden de marcha (kg)",
  KgPorHP: "Kg/HP",
  Neumaticos: "Neumáticos",
  LlantasAleacion: "Llantas de aleación",
  DiametroLlantas: "Diámetro llantas (pulg.)",
  TPMS: "TPMS (sensor presión neumáticos)",
  KitInflableAntiPinchazo: "Kit inflable anti-pinchazo",
  RuedaAuxHomogenea: "Rueda auxiliar homogénea",
  // --- Mecánica ---
  Cilindros: "Cilindros",
  Valvulas: "Válvulas",
  Inyeccion: "Inyección",
  Traccion: "Tracción",
  Suspension: "Suspensión",
  Caja: "Tipo de Caja Automática",
  MarchasVelocidades: "Marchas / velocidades",
  Turbo: "Turbo",
  NumeroPuertas: "Número de puertas",
  Aceite: "Aceite",
  Norma: "Norma",
  StartStop: "Start / Stop",
  // --- Consumo y emisiones ---
  CO2_g_km: "CO₂ (g/km)",
  ConsumoRuta: "Consumo ruta (l/100km)",
  ConsumoUrbano: "Consumo urbano (l/100km)",
  ConsumoMixto: "Consumo mixto (l/100km)",
  // --- Garantía ---
  GarantiaAnios: "Garantía (años)",
  GarantiaKm: "Garantía (km)",
  GarantiasDiferenciales: "Garantías diferenciales",
  // --- Eléctrico / Híbrido ---
  TipoVehiculoElectrico: "Tipo vehículo eléctrico / híbrido",
  EPedal: "E-Pedal",
  CapacidadTanqueHidrogeno: "Capacidad tanque hidrógeno",
  AutonomiaMaxRange: "Autonomía máxima (km)",
  AutonomiaMotorElectricoBEVPHEV: "Autonomía motor eléctrico BEV/PHEV (km)",
  CicloNorma: "Ciclo / norma",
  PotenciaMotor: "Potencia motor",
  CapacidadOperativaBateria: "Capacidad operativa batería",
  ParMotorTorque: "Par motor / torque",
  PotenciaCargaMax: "Potencia de carga máxima",
  TiposConectores: "Tipos de conectores",
  GarantiaCapBat: "Garantía cap. batería",
  TecnologiaBat: "Tecnología batería",
  TiempoCarga: "Tiempo de carga",
  CodigoFichaTecnica: "Código ficha técnica",
  // --- Confort e interior ---
  SistemaClimatizacion: "Sistema climatización",
  Direccion: "Dirección",
  TipoBloqueo: "Tipo de bloqueo",
  KeylessSmartKey: "Keyless / Smart Key",
  LevantaVidrios: "Levantavidrios",
  EspejosElectricos: "Espejos eléctricos",
  EspejoInteriorElectrocromado: "Espejo interior electrocromado",
  EspejosAbatiblesElectricamente: "Espejos abatibles eléctricamente",
  Tapizado: "Tapizado",
  VolanteRevestidoCuero: "Volante revestido en cuero",
  TablerDigital: "Tablero Digital",
  Computadora: "Computadora a bordo",
  GPS: "GPS",
  VelocidadCrucero: "Control velocidad crucero",
  Inmovilizador: "Inmovilizador",
  Alarma: "Alarma",
  // --- Seguridad activa ---
  ABAG: "Airbags",
  SRI: "Sistema Retención Infantil",
  ABS: "ABS",
  EBD_EBV_REF: "EBD / EBV / REF",
  DiscosFrenos: "Discos / frenos",
  FrenoEstacionamientoElectrico: "Freno de estacionamiento eléctrico",
  ESP_ControlEstabilidad: "ESP / Control Estabilidad",
  ControlTraccion: "Control de tracción",
  AsistFrenadoDetectorDistancia: "Asist. frenado / detector distancia",
  AsistPendiente: "Asistencia en pendiente",
  DetectorCambioFila: "Detector cambio de fila",
  DetectorPuntoCiego: "Detector punto ciego",
  TrafficSignRecognition: "Reconocimiento señales de tráfico",
  DriverAttentionControl: "Control atención del conductor",
  DetectorLluvia: "Detector de lluvia",
  GripControl: "Grip Control",
  LimitadorVelocidad: "Limitador de velocidad",
  AsistDescensoHDC: "Asistencia de descenso (HDC)",
  PaddleShift: "Paddle Shift",
  // --- Multimedia y conectividad ---
  ComandoAudioVolante: "Comando audio en volante",
  CD: "CD",
  MP3: "MP3",
  USB: "USB",
  Bluetooth: "Bluetooth",
  DVD: "DVD",
  MirrorScreen: "Mirror Screen",
  SistemaMultimedia: "Sistema multimedia",
  PantallaMultimediaPulgadas: "Pantalla multimedia (pulgadas)",
  PantallaTactil: "Pantalla táctil",
  CargadorSmartphoneInduccion: "Cargador smartphone por inducción",
  KitHiFi: "Kit HiFi",
  Radio: "Radio",
  // --- Asientos ---
  NumeroAsientos: "Número de asientos",
  AsientoElectricoCalefMasaje: "Asiento eléctrico / calef. / masaje",
  AsientosRango2y3: "Asientos rango 2 y 3",
  Asiento2Mas1: "Asiento 2+1",
  ButacaElectrica: "Butaca eléctrica",
  AsientoVentilado: "Asiento ventilado",
  AsientosMasajeador: "Asientos con masajeador",
  ApoyabrazosDelantero: "Apoyabrazos delantero",
  ApoyabrazosCentralTrasero: "Apoyabrazos central trasero",
  SoporteMusloDelantero: "Soporte de muslo delantero",
  AsientoTraseroAjusteElectrico: "Asiento trasero ajuste eléctrico",
  TerceraFilaAsientosElectricos: "3ra fila de asientos eléctricos",
  TipoAlturaAsientoDelantero: "Tipo / altura asiento delantero",
  SeatAdjustmentMemoryDriver: "Memoria asiento conductor",
  SeatAdjustmentMemoryCoDriver: "Memoria asiento acompañante",
  LumbarAdjustmentFrontDriver: "Ajuste lumbar conductor",
  LumbarAdjustmentFrontCoDriver: "Ajuste lumbar acompañante",
  SeatHeatingRear: "Calefacción asientos traseros",
  // --- Techo y exterior ---
  Techo: "Techo",
  TechoBiTono: "Techo bi-tono",
  BarrasTecho: "Barras de techo",
  NumeroTechosQueSeAbren: "Número de techos que se abren",
  // --- Estacionamiento y cámara ---
  SensorEstacionamiento: "Sensor de estacionamiento",
  Camara: "Cámara",
  SistemaAutomaticoEstacionamiento: "Sistema automático de estacionamiento",
  // --- Iluminación ---
  FarosNeblina: "Faros de niebla",
  FarosDireccionales: "Faros direccionales",
  FarosFullLED: "Faros Full LED",
  FarosHalogenosDRL_LED: "Faros halógenos / DRL LED",
  FarosXenonLimpiadores: "Faros xenón / limpiadores",
  PackVisibilidad: "Pack visibilidad",
  PasoLucesCruzRutaAutomatica: "Paso de luces cruce/ruta automático",
  VisionNocturna: "Visión nocturna",
  FarosMatrix: "Faros Matrix",
  LucesTraserasLED: "Luces traseras LED",
  LucesTraserasOLED: "Luces traseras OLED",
  // --- Maletero / carga ---
  MaleteraAperturaElectrica: "Maletero apertura eléctrica",
  CapacidadBaul: "Capacidad baúl (L)",
  CapacidadTanqueCombustible: "Capacidad tanque combustible (L)",
  ProtectorCaja: "Protector de caja",
  ParticionCabina: "Partición de cabina",
  NumPuertasLaterales: "N° puertas laterales",
  PuertaLateralElectrica: "Puerta lateral eléctrica",
  CargaUtil_kg: "Carga útil (kg)",
  VolumenUtil_m3: "Volumen útil (m³)",
  TipoAlturaUL: "Tipo / altura carga útil",
  CapacidadCargaCamiones: "Capacidad carga camiones",
  // --- Seguridad avanzada ---
  AlertaTraficoCruzadoTrasero: "Alerta tráfico cruzado trasero",
  AlertaTraficoCruzadoFrontal: "Alerta tráfico cruzado frontal",
  FrenadoMulticolision: "Frenado multicolisión",
  HeadUpDisplay: "Head Up Display",
  CityStop: "City Stop",
  FrenoPeatones: "Frenado peatones",
  BloqueDiferencialTerreno: "Bloqueo diferencial por terreno",
  DesempaniadorElectrico: "Desempañador eléctrico",
  IluminacionAmbiental: "Iluminación ambiental",
  LimpiaLavaParabrisasTrasero: "Limpia/lava parabrisas trasero",
  BlackWheelFrame: "Black Wheel Frame",
  VolanteMultifuncion: "Volante multifunción",
  TablerDigital3D: "Tablero Digital 3D",
  // --- Performance y tech avanzada ---
  AceleracionBEV_0a100: "Aceleración BEV 0-100 km/h (s)",
  AccelerationICE: "Aceleración ICE 0-100 km/h (s)",
  CargaElectricaWireless: "Carga eléctrica wireless",
  CargaElectricaInduccion: "Carga eléctrica por inducción",
  CableElectricoTipo3Incluido: "Cable eléctrico tipo 3 incluido",
  ChassisDriveSelect: "Chassis Drive Select",
  ChassisSportSuspension: "Chassis suspensión sport",
  DireccionCuatroRuedas: "Dirección en cuatro ruedas",
  LucesLaser: "Luces láser",
  DashboardDisplayConfigurable: "Dashboard display configurable",
  WirelessSmartphoneIntegration: "Wireless smartphone integration",
  MobilePhoneAntenna: "Antena teléfono móvil",
  DeflectorViento: "Deflector de viento",
  AsientosDeportivos: "Asientos deportivos",
};

// Etiqueta legible para una columna; si no está en el mapa, humaniza el nombre.
export const labelEquip = (col: string): string =>
  EQUIP_LABELS[col] || col.replace(/_/g, ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/\s+/g, ' ').trim();
